### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Ambrevar** [zwild/eshell-prompt-extras#27]
Would you mind releasing a new version?

**Comment by xuchunyang** [comment]
That would be great for the Melpa-stable users. I can push a tag tomorrow.

**Comment by Ambrevar** [comment]
Friendly ping in case you forgot ;)

**Comment by xuchunyang** [comment]
Hmm, there is an existing tag named 0.96, I don't understand its meaning. and I'm just going to create a 1.0 tag.

**Comment by Ambrevar** [comment]
Thanks!  I'll bump the Guix package just now then.
