### ISSUE TITLE
Remove the Git information in EShell

### ISSUE THREAD

**Issue by GabrielFrigo4** [zwild/eshell-prompt-extras#41]
Basically when I'm in a "git" directory the eshell with epe is extremely slow (it takes about 1s to refresh the screen after I run the command). I know this is not the fault of epe, but rather of git status which is extremely slow here on my computer (powershell and zsh suffer from this same problem because of the theme that shows git information).

But I don't care about the git information, so I'd like to disable this functionality. How do I do that?

**Comment by zwild** [comment]
Currently the code doesn't have this flat, but you could try this hack.

`(advice-add 'epe-git-p :override
              (lambda (&rest args)
                "Disable git info."
                nil))`

**Comment by suzzvv** [comment]
Currently the code doesn't have this flag, but you could try this hack.

```
(advice-add 'epe-git-p :override
                    (lambda (&rest args)
                      "Disable git info."
                      nil))
```

**Comment by GabrielFrigo4** [comment]
> Currently the code doesn't have this flag, but you could try this hack.
> 
> ```
> (advice-add 'epe-git-p :override
>                     (lambda (&rest args)
>                       "Disable git info."
>                       nil))
> ```

Thank you 
That worked.
It would be possible to add this in the project's README? I think it would help some people who would also like to remove git

**Comment by suzzvv** [comment]
There should be a flag to control this behavior. But I don't have time to add  that.
I will update the README when someone add a pr to support this.
